<?php include 'config.php' ?>
<!DOCTYPE html>
<html>
    <head>
        <?php head(); ?>
    </head>
    <body>
        <div class="container" style="text-align: justify;">
            <?php navbar(); ?>
            <h2>Undertaking with respect to BIT Mesra IT Usage Policy</h2>
            <br>
            <h4>The following Rules & Regulations must be accepted before you can register.</h4>
            <p>Whom this Document Concerns: All Users of IT infrastructure at BIT Mesra.
                <br>Reason for Policy: This policy outlines the responsible use of the Information Technology Infrastructure at BIT Mesra.
                <br>Statement of Policy: All users of BIT Mesra will be subject to the following Acceptable Use Policy.</p>
            <br>
            <p><b>Content</b> : I shall be responsible for all use of this network. In case I own a computer and decide to connect it to BIT Mesra network, I will be responsible for all the content on it, especially that which I make available to other users. (This provision will also apply to any computer or device for which I am responsible, and is included in the meaning of "my computer".) In case I do not own a computer but am provided some IT resources by BIT Mesra, I will be held responsible for the content stored in the designated workspace allotted to me (examples: file storage area, web pages, stored/archived emails, on Computer Centre or Department machines).</p>
            <p><b>Network</b> : I will be held responsible for all the network traffic generated by "my computer". I understand that network capacity is a limited, shared resource. I agree that physically tampering with network connections/equipments, sending disruptive signals, or making EXCESSIVE USE of network resources is strictly prohibited. Repeated offenses of this type could result in permanent disconnection of network services. I shall not share the network connection beyond my own use and will not act as a forwarder/masquerader for anyone else.</p>
            <p><b>Academic Use</b> : I understand that the IT infrastructure at BIT Mesra is for academic use and I shall not use it for any commercial purpose or to host data services for other people or groups. Also, I shall not host or broadcast information that might harm others or may be otherwise considered objectionable or illegal as per Indian law.</p>
            <p><b>Identity</b> : I shall not attempt to deceive others about my identity in electronic communications or network traffic. I will also not use BIT Mesra IT resources to threaten, intimidate, or harass others.</p>
            <p><b>Privacy</b> : I will not intrude on privacy of anyone. In particular I will not try to access computers (hacking), accounts, files, or information belonging to others without their knowledge and explicit consent.</p>
            <p><b>Monitoring</b> : I understand that the IT resources provided to me are subject to monitoring, with cause, as determined through consultation with the BIT Mesra administration, when applicable. The monitoring may include aggregate bandwidth usage to effectively manage limited IT resources as well as monitoring traffic content in response to a legal or law enforcement request to do so. I authorize BIT Mesra administration to perform network vulnerability and port scans on my systems, as needed, for protecting the overall integrity and efficiency of BIT Mesra network.</p>
            <p><b>Viruses</b> : I shall maintain my computer on this network with current virus detection software and current updates of my operating system, and I shall attempt to keep my computer free from viruses, worms, trojans, and other similar programs.</p>
            <p><b>File Sharing</b> : I shall not use the IT infrastructure to engage in any form of illegal file sharing (examples: copyrighted material, obscene material).</p>
            <p><b>Security</b> : I understand that I will not take any steps that endanger the security of the BIT Mesra network. Specifically, I will not attempt to bypass firewalls and access rules in place. This includes not setting up servers of any kind (examples: web, mail, proxy, DC++ Hubs) or any other softwares without concern of network team. In critical situations, BIT Mesra authorities reserve the right to disconnect any device or disable any account if it believed that either is involved in compromising the information security of BIT Mesra.</p>
            <p><b>Settings</b> : I understand that I will no change or tamper any settings for the network setup which are done by the Network team.</p>
            <p><b>Penalties</b> : I understand that any use of IT infrastructure at BIT Mesra that constitutes a violation of BIT Mesra Regulations could result in administrative or disciplinary procedures.</p>
            <?php footer(); ?>
        </div>
    </body>
</html>